enum Status {P1_WINS, P2_WINS, DRAW, IN_PROGRESS, RESET}
enum Move {FOLD, CHECK, CALL, RAISE, ALL_IN, BLIND}
enum Player {P1, P2}
enum Suit {CLUB, DIAMOND, HEART, SPADE}
enum Value {ACE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN, JACK, QUEEN, KING}
enum Stage {PREFLOP, FLOP, TURN, RIVER, SHOWDOWN}
